
import { ethers } from "ethers";
import fs from "fs/promises";
import crypto from "crypto";
import 'dotenv/config'; // Use environment variables

// This ABI is generated by Hardhat
import ProposalRegistryABI from '../artifacts/contracts/ProposalRegistry.sol/ProposalRegistry.json' assert { type: "json" };

let provider;
let signer;
let contract;

// This function initializes the connection to the blockchain
async function init() {
  if (contract) return; // Already initialized

  try {
    // Read configuration from environment variables
    const rpcUrl = process.env.BLOCKCHAIN_RPC_URL;
    const privateKey = process.env.WALLET_PRIVATE_KEY;
    const contractAddress = process.env.CONTRACT_ADDRESS;

    if (!rpcUrl || !privateKey || !contractAddress) {
      throw new Error("Blockchain environment variables are not configured.");
    }

    provider = new ethers.JsonRpcProvider(rpcUrl);
    signer = new ethers.Wallet(privateKey, provider);
    contract = new ethers.Contract(contractAddress, ProposalRegistryABI.abi, signer);

    console.log("✅ Blockchain client initialized successfully.");
    console.log("Connected to contract at:", await contract.getAddress());
    console.log("Using wallet address:", signer.address);

  } catch (error) {
    console.error("❌ Failed to initialize blockchain client:", error.message);
    // Set contract to null to indicate failure
    contract = null;
  }
}

// Call init on startup
init();

// --- Public Functions ---

export async function storeProposalRecordWithMeta(proposalId, cid, fileHash, parentHash, versionNumber, versionType, note) {
  if (!contract) throw new Error("Blockchain client is not initialized.");
  const tx = await contract.storeProposalRecordWithMeta(
    proposalId, cid, fileHash, parentHash, versionNumber, versionType, note
  );
  return await tx.wait();
}

export async function getRecordsByProposal(proposalId) {
  if (!contract) throw new Error("Blockchain client is not initialized.");
  return await contract.getRecordsByProposal(proposalId);
}

// Add other functions as needed...
