/**
 * AI Service - Mocked implementation
 * In production, this will call the actual Python AI backend
 */

class AIService {
  /**
   * Generate AI evaluation report for a proposal
   * This is a MOCKED implementation
   */
  async evaluateProposal(proposalData) {
    try {
      // Simulate AI processing time
      await this.delay(2000);

      // Mock AI evaluation response
      const mockEvaluation = {
        success: true,
        score: this.generateMockScore(),
        evaluationSummary: {
          novelty: this.generateMockScore(),
          feasibility: this.generateMockScore(),
          benefit: this.generateMockScore(),
          costValidity: this.generateMockScore(),
          technicalSoundness: this.generateMockScore()
        },
        recommendations: [
          'Consider expanding the methodology section with more technical details',
          'Budget allocation should be justified with detailed breakdown',
          'Timeline appears feasible but contingency planning recommended'
        ],
        concerns: [
          'Limited discussion on environmental impact',
          'Risk mitigation strategies need more detail'
        ],
        aiReport: this.generateMockPDFBuffer(proposalData)
      };

      return mockEvaluation;
    } catch (error) {
      console.error('AI evaluation error:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Generate plagiarism check report
   * This is a MOCKED implementation
   */
  async checkPlagiarism(content) {
    try {
      await this.delay(1500);

      return {
        success: true,
        overallSimilarity: Math.floor(Math.random() * 15) + 1, // 1-15%
        sources: [
          {
            text: 'Sample matching text...',
            similarity: Math.floor(Math.random() * 10) + 1,
            source: 'Research paper from academic database'
          }
        ]
      };
    } catch (error) {
      console.error('Plagiarism check error:', error);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Generate mock PDF buffer for AI report
   */
  generateMockPDFBuffer(proposalData) {
    // In real implementation, this would generate actual PDF
    // For now, return a mock buffer that represents a PDF
    const mockPDFContent = `
AI EVALUATION REPORT
====================

Proposal ID: ${proposalData.proposalCode}
Title: ${proposalData.title}
Date: ${new Date().toISOString()}

EVALUATION SUMMARY
------------------
Overall Score: ${this.generateMockScore()}/100

Novelty: ${this.generateMockScore()}/100
- The proposed approach shows moderate innovation in the field

Feasibility: ${this.generateMockScore()}/100
- Technical feasibility is well demonstrated
- Resource allocation appears adequate

Benefit to Industry: ${this.generateMockScore()}/100
- Clear potential benefits to coal mining sector
- Economic impact well justified

Cost Validation: ${this.generateMockScore()}/100
- Budget breakdown is reasonable
- Cost estimates align with industry standards

Technical Soundness: ${this.generateMockScore()}/100
- Methodology is scientifically sound
- References to relevant literature provided

RECOMMENDATIONS
---------------
1. Consider expanding the methodology section with more technical details
2. Budget allocation should be justified with detailed breakdown
3. Timeline appears feasible but contingency planning recommended

CONCERNS
--------
1. Limited discussion on environmental impact
2. Risk mitigation strategies need more detail

This is an automated AI-generated evaluation report.
Generated by NaCCER AI System
`;

    return Buffer.from(mockPDFContent, 'utf-8');
  }

  /**
   * Helper: Generate random score between 60-95
   */
  generateMockScore() {
    return Math.floor(Math.random() * 35) + 60;
  }

  /**
   * Helper: Simulate async delay
   */
  delay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  /**
   * Call actual AI backend (to be implemented)
   */
  async callAIBackend(endpoint, data) {
    // Future implementation:
    // const response = await axios.post(`${process.env.AI_BACKEND_URL}${endpoint}`, data);
    // return response.data;
    
    throw new Error('AI Backend integration not yet implemented');
  }
}

export default new AIService();
